/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.srohter.LauncherX.MainMenu;

import com.srohter.LauncherX.LoginMenu.Toaster.Toaster;
import com.srohter.LauncherX.database.Utils.ButtonStyle;
import com.srohter.LauncherX.database.Utils.UIUtils;
import com.srohter.LauncherX.database.Utils.Colors;
import com.sun.tools.javac.Main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Objects;
import java.util.Set;

/**
 * @author Skylar Rohter
 * @since 1.0
 */
public class MainMenu extends JFrame {

    /**
     * Creates new form Login
     */
    public MainMenu() {
        setBounds((UIUtils.width-1080)-(1080/4),(UIUtils.height-759)-(759/4),1080,759);
        setUndecorated(true);
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        loginButton = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogoBorder = new javax.swing.JPanel();
        OpenersBtn = new javax.swing.JLabel();
        assBtn = new javax.swing.JLabel();
        browBtn = new javax.swing.JLabel();
        setBtn = new javax.swing.JLabel();
        winBtns = new javax.swing.JPanel();
        sBtn = new javax.swing.JLabel();
        mBtn = new javax.swing.JLabel();
        xBtn = new javax.swing.JLabel();
        DefaultPanel = new javax.swing.JPanel();
        lxicon = new JLabel();
        OpenersPanel = new JPanel();
        AssPanel = new JPanel();
        BrowPanel = new JPanel();
        SetPanel = new JPanel();
        ScrollAss = new JScrollPane();
        AssTable = new JTable();


        //Toaster
        toaster = new Toaster(MenuPanel);

        OpenersPanel.setVisible(false);
        AssPanel.setVisible(false);
        BrowPanel.setVisible(false);
        SetPanel.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(Colors.BACKGROUND_COLOR);
        MainPanel.setForeground(new java.awt.Color(255, 51, 102));

        MenuPanel.setBackground(UIUtils.COLOR_BACKGROUND_DARKER);

        jLabel1.setIcon(new ImageIcon(Objects.requireNonNull(getClass().getClassLoader().getResource("ok.png")).getFile())); // NOI18N

        LogoBorder.setBackground(Colors.BACKGROUND_COLOR);
        LogoBorder.setBorder(new javax.swing.border.LineBorder(UIUtils.COLOR_INTERACTIVE, 2, true));
        LogoBorder.setPreferredSize(new java.awt.Dimension(280, 6));

        javax.swing.GroupLayout LogoBorderLayout = new javax.swing.GroupLayout(LogoBorder);
        LogoBorder.setLayout(LogoBorderLayout);
        LogoBorderLayout.setHorizontalGroup(
                LogoBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        LogoBorderLayout.setVerticalGroup(
                LogoBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        OpenersBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
        OpenersBtn.setFont(UIUtils.FONT_GENERAL_UI); // NOI18N
        OpenersBtn.setForeground(UIUtils.COLOR_BACKGROUND);
        OpenersBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpenersBtn.setText("Openers");
        OpenersBtn.setOpaque(true);
        OpenersBtn.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toaster.warn("Hello");
                DefaultPanel.setVisible(false);
                AssPanel.setVisible(false);
                BrowPanel.setVisible(false);
                SetPanel.setVisible(false);
                OpenersPanel.setVisible(true);//TRUE
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                OpenersBtn.setBackground(UIUtils.COLOR_INTERACTIVE_DARKER);
                OpenersBtn.setForeground(UIUtils.COLOR_BACKGROUND_DARKER);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                OpenersBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
                OpenersBtn.setForeground(UIUtils.COLOR_BACKGROUND);
            }
        });


        assBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
        assBtn.setFont(UIUtils.FONT_GENERAL_UI); // NOI18N
        assBtn.setForeground(UIUtils.COLOR_BACKGROUND);
        assBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assBtn.setText("Assignments");
        assBtn.setOpaque(true);
        assBtn.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DefaultPanel.setVisible(false);
                OpenersPanel.setVisible(false);
                BrowPanel.setVisible(false);
                SetPanel.setVisible(false);
                AssPanel.setVisible(true);//TRUE
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                assBtn.setBackground(UIUtils.COLOR_INTERACTIVE_DARKER);
                assBtn.setForeground(UIUtils.COLOR_BACKGROUND_DARKER);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                assBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
                assBtn.setForeground(UIUtils.COLOR_BACKGROUND);
            }
        });

        browBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
        browBtn.setFont(UIUtils.FONT_GENERAL_UI); // NOI18N
        browBtn.setForeground(UIUtils.COLOR_BACKGROUND);
        browBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        browBtn.setText("Browser");
        browBtn.setOpaque(true);
        browBtn.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DefaultPanel.setVisible(false);
                OpenersPanel.setVisible(false);
                SetPanel.setVisible(false);
                AssPanel.setVisible(false);
                BrowPanel.setVisible(true);//TRUE
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                browBtn.setBackground(UIUtils.COLOR_INTERACTIVE_DARKER);
                browBtn.setForeground(UIUtils.COLOR_BACKGROUND_DARKER);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                browBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
                browBtn.setForeground(UIUtils.COLOR_BACKGROUND);
            }
        });

        setBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
        setBtn.setFont(UIUtils.FONT_GENERAL_UI); // NOI18N
        setBtn.setForeground(UIUtils.COLOR_BACKGROUND);
        setBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setBtn.setText("Settings");
        setBtn.setOpaque(true);
        setBtn.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DefaultPanel.setVisible(false);
                OpenersPanel.setVisible(false);
                BrowPanel.setVisible(false);
                AssPanel.setVisible(false);
                SetPanel.setVisible(true);//TRUE
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                setBtn.setBackground(UIUtils.COLOR_INTERACTIVE_DARKER);
                setBtn.setForeground(UIUtils.COLOR_BACKGROUND_DARKER);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                setBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
                setBtn.setForeground(UIUtils.COLOR_BACKGROUND);
            }
        });

        winBtns.setBackground(Colors.BACKGROUND_COLOR);
        winBtns.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sBtn.setIcon(new ImageIcon(Objects.requireNonNull(getClass().getClassLoader().getResource("rec.png")).getFile())); // NOI18N
        sBtn.setToolTipText("");
        sBtn.setSize(new java.awt.Dimension(48, 48));

        mBtn.setIcon(new ImageIcon(Objects.requireNonNull(getClass().getClassLoader().getResource("m.png")).getFile()));// NOI18N
        mBtn.setToolTipText("");
        mBtn.setSize(new java.awt.Dimension(48, 48));

        xBtn.setIcon(new ImageIcon(Objects.requireNonNull(getClass().getClassLoader().getResource("x.png")).getFile())); // NOI18N
        xBtn.setToolTipText("");
        xBtn.setSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
                MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuPanelLayout.createSequentialGroup()
                                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuPanelLayout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jLabel1))
                                        .addGroup(MenuPanelLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(setBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(browBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(assBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(OpenersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(MenuPanelLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(LogoBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
                MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addGap(20,20,20)
                                .addComponent(LogoBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(OpenersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(assBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(browBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(setBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))
        );

        lxicon.setIcon(new ImageIcon(Objects.requireNonNull(getClass().getClassLoader().getResource("lx.png")).getFile()));

        javax.swing.GroupLayout DefaultPanelLayout = new javax.swing.GroupLayout(DefaultPanel);
        DefaultPanel.setBackground(UIUtils.COLOR_BACKGROUND);
        DefaultPanel.setLayout(DefaultPanelLayout);
        DefaultPanelLayout.setHorizontalGroup(
                DefaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DefaultPanelLayout.createSequentialGroup()
                                .addContainerGap(233, Short.MAX_VALUE)
                                .addComponent(lxicon, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(209, 215, 220))
        );
        DefaultPanelLayout.setVerticalGroup(
                DefaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DefaultPanelLayout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(lxicon, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DefaultPanel.setVisible(true);

        //*********************************************************************************************************************************************


        javax.swing.GroupLayout OpenersPanelLayout = new javax.swing.GroupLayout(OpenersPanel);
        OpenersPanel.setBackground(Color.RED);
        OpenersPanel.setLayout(OpenersPanelLayout);
        OpenersPanelLayout.setHorizontalGroup(
                OpenersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 803, Short.MAX_VALUE)
        );
        OpenersPanelLayout.setVerticalGroup(
                OpenersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 740, Short.MAX_VALUE)
        );


        //*********************************************************************************************************************************************


        AssTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {"10/10/2022", "IB Bio Textbool analysis", "Biology", null},
                        {"10/14/2022", "BioQuiz1", "Mathamatics", null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Due Date", "Name", "Class", "Notes"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        AssTable.getTableHeader().setReorderingAllowed(false);
        ScrollAss.setViewportView(AssTable);
        if (AssTable.getColumnModel().getColumnCount() > 0) {
            AssTable.getColumnModel().getColumn(0).setResizable(false);
            AssTable.getColumnModel().getColumn(1).setResizable(false);
            AssTable.getColumnModel().getColumn(2).setResizable(false);
            AssTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout AssPanelLayout = new javax.swing.GroupLayout(AssPanel);
        AssPanel.setLayout(AssPanelLayout);
        AssPanelLayout.setHorizontalGroup(
                AssPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ScrollAss, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        AssPanelLayout.setVerticalGroup(
                AssPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ScrollAss, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
        );


        //*********************************************************************************************************************************************


        javax.swing.GroupLayout BrowPanelLayout = new javax.swing.GroupLayout(BrowPanel);
        BrowPanel.setBackground(Color.GREEN);
        BrowPanel.setLayout(BrowPanelLayout);
        BrowPanelLayout.setHorizontalGroup(
                BrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 803, Short.MAX_VALUE)
        );
        BrowPanelLayout.setVerticalGroup(
                BrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 740, Short.MAX_VALUE)
        );


        //*********************************************************************************************************************************************


        javax.swing.GroupLayout SetPanelLayout = new javax.swing.GroupLayout(SetPanel);
        SetPanel.setBackground(Color.YELLOW);
        SetPanel.setLayout(SetPanelLayout);
        SetPanelLayout.setHorizontalGroup(
                SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 803, Short.MAX_VALUE)
        );
        SetPanelLayout.setVerticalGroup(
                SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 740, Short.MAX_VALUE)
        );


        //*********************************************************************************************************************************************

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DefaultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OpenersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AssPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BrowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

        );
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DefaultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OpenersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AssPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BrowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    private void addOpenersButton(JPanel panel1) {
        final Color[] loginButtonColors = {UIUtils.COLOR_INTERACTIVE, Color.white};

        JLabel loginButton = new JLabel() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = UIUtils.get2dGraphics(g);
                super.paintComponent(g2);

                Insets insets = getInsets();
                int w = getWidth() - insets.left - insets.right;
                int h = getHeight() - insets.top - insets.bottom;
                g2.setColor(loginButtonColors[0]);
                g2.fillRoundRect(insets.left, insets.top, w, h, UIUtils.ROUNDNESS, UIUtils.ROUNDNESS);

                FontMetrics metrics = g2.getFontMetrics(UIUtils.FONT_GENERAL_UI);
                int x2 = (getWidth() - metrics.stringWidth(UIUtils.BUTTON_TEXT_LOGIN)) / 2;
                int y2 = ((getHeight() - metrics.getHeight()) / 2) + metrics.getAscent();
                g2.setFont(UIUtils.FONT_GENERAL_UI);
                g2.setColor(loginButtonColors[1]);
                g2.drawString(UIUtils.BUTTON_TEXT_LOGIN, x2, y2);
            }
        };

        loginButton.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                //loginEventHandler();
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                loginButtonColors[0] = UIUtils.COLOR_INTERACTIVE_DARKER;
                loginButtonColors[1] = UIUtils.OFFWHITE;
                loginButton.repaint();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                loginButtonColors[0] = UIUtils.COLOR_INTERACTIVE;
                loginButtonColors[1] = Color.white;
                loginButton.repaint();
            }
        });
        panel1.add(loginButton);
    }

    private void OpenersBtnActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Called");
        DefaultPanel.setVisible(false);
        OpenersPanel.setVisible(true);
        System.out.println(".");
    }

    private void setBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void OpenersBtnMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }


    public void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private JLabel loginButton = new JLabel() {
        @Override
        protected void paintComponent(Graphics g) {
            final Color[] loginButtonColors = {UIUtils.COLOR_INTERACTIVE, Color.white};
            Graphics2D g2 = UIUtils.get2dGraphics(g);
            super.paintComponent(g2);

            Insets insets = getInsets();
            int w = getWidth() - insets.left - insets.right;
            int h = getHeight() - insets.top - insets.bottom;
            g2.setColor(loginButtonColors[0]);
            g2.fillRoundRect(insets.left, insets.top, w, h, UIUtils.ROUNDNESS, UIUtils.ROUNDNESS);

            FontMetrics metrics = g2.getFontMetrics(UIUtils.FONT_GENERAL_UI);
            int x2 = (getWidth() - metrics.stringWidth(UIUtils.BUTTON_TEXT_LOGIN)) / 2;
            int y2 = ((getHeight() - metrics.getHeight()) / 2) + metrics.getAscent();
            g2.setFont(UIUtils.FONT_GENERAL_UI);
            g2.setColor(loginButtonColors[1]);
            g2.drawString(UIUtils.BUTTON_TEXT_LOGIN, x2, y2);

            loginButton.setBackground(UIUtils.COLOR_BACKGROUND);
            loginButton.setBounds(10, 10, 250, 44);
            loginButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        }
    };
    private JLabel AccentLabel;
    private JPanel LogoBorder;
    private JPanel MainPanel;
    private JPanel MenuPanel;
    private JLabel OpenersBtn;
    private JLabel assBtn;
    private JLabel browBtn;
    private JPanel DefaultPanel;
    private JLabel jLabel1;
    private javax.swing.JLabel mBtn;
    private javax.swing.JLabel sBtn;
    private javax.swing.JLabel setBtn;
    private javax.swing.JPanel winBtns;
    private javax.swing.JLabel xBtn;
    private JLabel lxicon;
    private JPanel OpenersPanel;
    private JPanel AssPanel;
    private JPanel BrowPanel;
    private JPanel SetPanel;
    private JScrollPane ScrollAss;
    private JTable AssTable;

    //Toaster
    private Toaster toaster;
    // End of variables declaration
}
