/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.srohter.LauncherX.MainMenu;

import com.srohter.LauncherX.LoginMenu.Toaster.Toaster;
import com.srohter.LauncherX.database.Utils.ButtonStyle;
import com.srohter.LauncherX.database.Utils.UIUtils;
import com.srohter.LauncherX.database.Utils.Colors;
import com.sun.tools.javac.Main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Objects;
import java.util.Set;

/**
 * @author Skylar Rohter
 * @since 1.0
 */
public class MainMenu extends JFrame {

    /**
     * Creates new form Login
     */
    public MainMenu() {
        setBounds((UIUtils.width-1080)-(1080/4),(UIUtils.height-759)-(759/4),1080,759);
        setUndecorated(true);
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        loginButton = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogoBorder = new javax.swing.JPanel();
        OpenersBtn = new javax.swing.JLabel();
        assBtn = new javax.swing.JLabel();
        browBtn = new javax.swing.JLabel();
        setBtn = new javax.swing.JLabel();
        winBtns = new javax.swing.JPanel();
        sBtn = new javax.swing.JLabel();
        mBtn = new javax.swing.JLabel();
        xBtn = new javax.swing.JLabel();
        DefaultPanel = new javax.swing.JPanel();
        lxicon = new JLabel();
        OpenersPanel = new JPanel();
        AssPanel = new JPanel();
        BrowPanel = new JPanel();
        SetPanel = new JPanel();
        ScrollAss = new JScrollPane();
        AssTable = new JTable();


        //SHOP PANEL

        pointsLabel = new javax.swing.JLabel();
        pointsCounter = new javax.swing.JLabel();
        pointsBar = new javax.swing.JProgressBar();
        ShopLabel = new javax.swing.JLabel();
        ShopBar = new javax.swing.JPanel();
        YellowPanel = new javax.swing.JPanel();
        YellowIcon = new javax.swing.JPanel();
        YellowLabel = new javax.swing.JLabel();
        OrangePanel = new javax.swing.JPanel();
        OrangeIcon = new javax.swing.JPanel();
        orangeLabel = new javax.swing.JLabel();
        RedPanel = new javax.swing.JPanel();
        RedIcon = new javax.swing.JPanel();
        RedLabel = new javax.swing.JLabel();
        AquaPanel = new javax.swing.JPanel();
        AquaIcon = new javax.swing.JPanel();
        AquaLabel = new javax.swing.JLabel();
        PurplePanel = new javax.swing.JPanel();
        PurpleIcon = new javax.swing.JPanel();
        PurpleLabel = new javax.swing.JLabel();
        PinkPanel = new javax.swing.JPanel();
        PinkIcon = new javax.swing.JPanel();
        PinkLabel = new javax.swing.JLabel();
        Colors = new javax.swing.JPanel();
        ColorsLabel = new javax.swing.JLabel();
        Color5 = new javax.swing.JPanel();
        Color6 = new javax.swing.JPanel();
        Color3 = new javax.swing.JPanel();
        Color1 = new javax.swing.JPanel();
        Color2 = new javax.swing.JPanel();
        Color4 = new javax.swing.JPanel();


        //Toaster
        toaster = new Toaster(AssPanel);

        OpenersPanel.setVisible(false);
        AssPanel.setVisible(false);
        BrowPanel.setVisible(false);
        SetPanel.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(UIUtils.COLOR_BACKGROUND);
        MainPanel.setForeground(new java.awt.Color(255, 51, 102));

        MenuPanel.setBackground(UIUtils.COLOR_BACKGROUND_DARKER);

        jLabel1.setIcon(new ImageIcon(Objects.requireNonNull(getClass().getClassLoader().getResource("ok.png")).getFile())); // NOI18N

        LogoBorder.setBackground(UIUtils.COLOR_BACKGROUND);
        LogoBorder.setBorder(new javax.swing.border.LineBorder(UIUtils.COLOR_INTERACTIVE, 2, true));
        LogoBorder.setPreferredSize(new java.awt.Dimension(280, 6));

        javax.swing.GroupLayout LogoBorderLayout = new javax.swing.GroupLayout(LogoBorder);
        LogoBorder.setLayout(LogoBorderLayout);
        LogoBorderLayout.setHorizontalGroup(
                LogoBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        LogoBorderLayout.setVerticalGroup(
                LogoBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        OpenersBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
        OpenersBtn.setFont(UIUtils.FONT_GENERAL_UI); // NOI18N
        OpenersBtn.setForeground(UIUtils.COLOR_BACKGROUND);
        OpenersBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpenersBtn.setText("Openers");
        OpenersBtn.setOpaque(true);
        OpenersBtn.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toaster.warn("Hello");
                DefaultPanel.setVisible(false);
                AssPanel.setVisible(false);
                BrowPanel.setVisible(false);
                SetPanel.setVisible(false);
                OpenersPanel.setVisible(true);//TRUE
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                OpenersBtn.setBackground(UIUtils.COLOR_INTERACTIVE_DARKER);
                OpenersBtn.setForeground(UIUtils.COLOR_BACKGROUND_DARKER);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                OpenersBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
                OpenersBtn.setForeground(UIUtils.COLOR_BACKGROUND);
            }
        });


        assBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
        assBtn.setFont(UIUtils.FONT_GENERAL_UI); // NOI18N
        assBtn.setForeground(UIUtils.COLOR_BACKGROUND);
        assBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assBtn.setText("Assignments");
        assBtn.setOpaque(true);
        assBtn.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DefaultPanel.setVisible(false);
                OpenersPanel.setVisible(false);
                BrowPanel.setVisible(false);
                SetPanel.setVisible(false);
                AssPanel.setVisible(true);//TRUE
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                assBtn.setBackground(UIUtils.COLOR_INTERACTIVE_DARKER);
                assBtn.setForeground(UIUtils.COLOR_BACKGROUND_DARKER);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                assBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
                assBtn.setForeground(UIUtils.COLOR_BACKGROUND);
            }
        });

        browBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
        browBtn.setFont(UIUtils.FONT_GENERAL_UI); // NOI18N
        browBtn.setForeground(UIUtils.COLOR_BACKGROUND);
        browBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        browBtn.setText("Shop");
        browBtn.setOpaque(true);
        browBtn.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DefaultPanel.setVisible(false);
                OpenersPanel.setVisible(false);
                SetPanel.setVisible(false);
                AssPanel.setVisible(false);
                BrowPanel.setVisible(true);//TRUE
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                browBtn.setBackground(UIUtils.COLOR_INTERACTIVE_DARKER);
                browBtn.setForeground(UIUtils.COLOR_BACKGROUND_DARKER);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                browBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
                browBtn.setForeground(UIUtils.COLOR_BACKGROUND);
            }
        });

        setBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
        setBtn.setFont(UIUtils.FONT_GENERAL_UI); // NOI18N
        setBtn.setForeground(UIUtils.COLOR_BACKGROUND);
        setBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setBtn.setText("Settings");
        setBtn.setOpaque(true);
        setBtn.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DefaultPanel.setVisible(false);
                OpenersPanel.setVisible(false);
                BrowPanel.setVisible(false);
                AssPanel.setVisible(false);
                SetPanel.setVisible(true);//TRUE
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                setBtn.setBackground(UIUtils.COLOR_INTERACTIVE_DARKER);
                setBtn.setForeground(UIUtils.COLOR_BACKGROUND_DARKER);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                setBtn.setBackground(UIUtils.COLOR_INTERACTIVE);
                setBtn.setForeground(UIUtils.COLOR_BACKGROUND);
            }
        });

        winBtns.setBackground(UIUtils.COLOR_BACKGROUND);
        winBtns.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sBtn.setIcon(new ImageIcon(Objects.requireNonNull(getClass().getClassLoader().getResource("rec.png")).getFile())); // NOI18N
        sBtn.setToolTipText("");
        sBtn.setSize(new java.awt.Dimension(48, 48));

        mBtn.setIcon(new ImageIcon(Objects.requireNonNull(getClass().getClassLoader().getResource("m.png")).getFile()));// NOI18N
        mBtn.setToolTipText("");
        mBtn.setSize(new java.awt.Dimension(48, 48));

        xBtn.setIcon(new ImageIcon(Objects.requireNonNull(getClass().getClassLoader().getResource("x.png")).getFile())); // NOI18N
        xBtn.setToolTipText("");
        xBtn.setSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
                MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuPanelLayout.createSequentialGroup()
                                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuPanelLayout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jLabel1))
                                        .addGroup(MenuPanelLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(setBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(browBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(assBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(OpenersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(MenuPanelLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(LogoBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
                MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addGap(20,20,20)
                                .addComponent(LogoBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(OpenersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(assBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(browBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(setBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))
        );

        lxicon.setIcon(new ImageIcon(Objects.requireNonNull(getClass().getClassLoader().getResource("lx.png")).getFile()));

        javax.swing.GroupLayout DefaultPanelLayout = new javax.swing.GroupLayout(DefaultPanel);
        DefaultPanel.setBackground(UIUtils.COLOR_BACKGROUND);
        DefaultPanel.setLayout(DefaultPanelLayout);
        DefaultPanelLayout.setHorizontalGroup(
                DefaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DefaultPanelLayout.createSequentialGroup()
                                .addContainerGap(233, Short.MAX_VALUE)
                                .addComponent(lxicon, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(209, 215, 220))
        );
        DefaultPanelLayout.setVerticalGroup(
                DefaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DefaultPanelLayout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(lxicon, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DefaultPanel.setVisible(true);

        //*********************************************************************************************************************************************


        javax.swing.GroupLayout OpenersPanelLayout = new javax.swing.GroupLayout(OpenersPanel);
        OpenersPanel.setBackground(Color.RED);
        OpenersPanel.setLayout(OpenersPanelLayout);
        OpenersPanelLayout.setHorizontalGroup(
                OpenersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 803, Short.MAX_VALUE)
        );
        OpenersPanelLayout.setVerticalGroup(
                OpenersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 740, Short.MAX_VALUE)
        );


        //*********************************************************************************************************************************************


        AssTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {"10/10/2022", "IB Bio Textbool analysis", "Biology", null},
                        {"10/14/2022", "BioQuiz1", "Mathamatics", null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Due Date", "Name", "Class", "Notes"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        AssTable.getTableHeader().setReorderingAllowed(false);
        ScrollAss.setViewportView(AssTable);
        if (AssTable.getColumnModel().getColumnCount() > 0) {
            AssTable.getColumnModel().getColumn(0).setResizable(false);
            AssTable.getColumnModel().getColumn(1).setResizable(false);
            AssTable.getColumnModel().getColumn(2).setResizable(false);
            AssTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout AssPanelLayout = new javax.swing.GroupLayout(AssPanel);
        AssPanel.setLayout(AssPanelLayout);
        AssPanelLayout.setHorizontalGroup(
                AssPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ScrollAss, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        AssPanelLayout.setVerticalGroup(
                AssPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ScrollAss, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
        );


        //*********************************************************************************************************************************************


        BrowPanel.setBackground(new java.awt.Color(37, 51, 61));

        pointsLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pointsLabel.setForeground(new java.awt.Color(127, 253, 253));
        pointsLabel.setText("Points: ");

        pointsCounter.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pointsCounter.setForeground(new java.awt.Color(127, 253, 253));
        pointsCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pointsCounter.setText("1000");

        pointsBar.setBackground(new java.awt.Color(25, 37, 46));
        pointsBar.setForeground(new java.awt.Color(127, 253, 253));

        ShopLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        ShopLabel.setForeground(new java.awt.Color(127, 253, 253));
        ShopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShopLabel.setText("Shop");
        ShopLabel.setToolTipText("");

        ShopBar.setBackground(new java.awt.Color(127, 253, 253));
        ShopBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 253, 253), 1, true));
        ShopBar.setForeground(new java.awt.Color(127, 253, 253));
        ShopBar.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout ShopBarLayout = new javax.swing.GroupLayout(ShopBar);
        ShopBar.setLayout(ShopBarLayout);
        ShopBarLayout.setHorizontalGroup(
                ShopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 98, Short.MAX_VALUE)
        );
        ShopBarLayout.setVerticalGroup(
                ShopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        YellowPanel.setBackground(new java.awt.Color(25, 37, 46));

        YellowIcon.setBackground(new java.awt.Color(255, 255, 204));
        YellowIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout YellowIconLayout = new javax.swing.GroupLayout(YellowIcon);
        YellowIcon.setLayout(YellowIconLayout);
        YellowIconLayout.setHorizontalGroup(
                YellowIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );
        YellowIconLayout.setVerticalGroup(
                YellowIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );

        YellowLabel.setBackground(new java.awt.Color(0, 0, 0));
        YellowLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        YellowLabel.setForeground(new java.awt.Color(255, 255, 204));
        YellowLabel.setText("> YELLOW - 6000");

        javax.swing.GroupLayout YellowPanelLayout = new javax.swing.GroupLayout(YellowPanel);
        YellowPanel.setLayout(YellowPanelLayout);
        YellowPanelLayout.setHorizontalGroup(
                YellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(YellowPanelLayout.createSequentialGroup()
                                .addComponent(YellowIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YellowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        YellowPanelLayout.setVerticalGroup(
                YellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(YellowIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(YellowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        OrangePanel.setBackground(new java.awt.Color(25, 37, 46));

        OrangeIcon.setBackground(new java.awt.Color(255, 204, 153));
        OrangeIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout OrangeIconLayout = new javax.swing.GroupLayout(OrangeIcon);
        OrangeIcon.setLayout(OrangeIconLayout);
        OrangeIconLayout.setHorizontalGroup(
                OrangeIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );
        OrangeIconLayout.setVerticalGroup(
                OrangeIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );

        orangeLabel.setBackground(new java.awt.Color(0, 0, 0));
        orangeLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        orangeLabel.setForeground(new java.awt.Color(255, 204, 153));
        orangeLabel.setText("> ORANGE - 5000");

        javax.swing.GroupLayout OrangePanelLayout = new javax.swing.GroupLayout(OrangePanel);
        OrangePanel.setLayout(OrangePanelLayout);
        OrangePanelLayout.setHorizontalGroup(
                OrangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(OrangePanelLayout.createSequentialGroup()
                                .addComponent(OrangeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orangeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        OrangePanelLayout.setVerticalGroup(
                OrangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(OrangePanelLayout.createSequentialGroup()
                                .addComponent(OrangeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(OrangePanelLayout.createSequentialGroup()
                                .addComponent(orangeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RedPanel.setBackground(new java.awt.Color(25, 37, 46));

        RedIcon.setBackground(new java.awt.Color(255, 102, 102));
        RedIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout RedIconLayout = new javax.swing.GroupLayout(RedIcon);
        RedIcon.setLayout(RedIconLayout);
        RedIconLayout.setHorizontalGroup(
                RedIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );
        RedIconLayout.setVerticalGroup(
                RedIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );

        RedLabel.setBackground(new java.awt.Color(0, 0, 0));
        RedLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        RedLabel.setForeground(new java.awt.Color(255, 102, 102));
        RedLabel.setText("> RED - 1000");

        javax.swing.GroupLayout RedPanelLayout = new javax.swing.GroupLayout(RedPanel);
        RedPanel.setLayout(RedPanelLayout);
        RedPanelLayout.setHorizontalGroup(
                RedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RedPanelLayout.createSequentialGroup()
                                .addComponent(RedIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        RedPanelLayout.setVerticalGroup(
                RedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(RedIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        AquaPanel.setBackground(new java.awt.Color(25, 37, 46));

        AquaIcon.setBackground(new java.awt.Color(127, 253, 253));
        AquaIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout AquaIconLayout = new javax.swing.GroupLayout(AquaIcon);
        AquaIcon.setLayout(AquaIconLayout);
        AquaIconLayout.setHorizontalGroup(
                AquaIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );
        AquaIconLayout.setVerticalGroup(
                AquaIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );

        AquaLabel.setBackground(new java.awt.Color(0, 0, 0));
        AquaLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        AquaLabel.setForeground(new java.awt.Color(127, 253, 253));
        AquaLabel.setText("> AQUA - FREE");

        javax.swing.GroupLayout AquaPanelLayout = new javax.swing.GroupLayout(AquaPanel);
        AquaPanel.setLayout(AquaPanelLayout);
        AquaPanelLayout.setHorizontalGroup(
                AquaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AquaPanelLayout.createSequentialGroup()
                                .addComponent(AquaIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AquaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        AquaPanelLayout.setVerticalGroup(
                AquaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AquaIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AquaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PurplePanel.setBackground(new java.awt.Color(25, 37, 46));

        PurpleIcon.setBackground(new java.awt.Color(153, 153, 255));
        PurpleIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout PurpleIconLayout = new javax.swing.GroupLayout(PurpleIcon);
        PurpleIcon.setLayout(PurpleIconLayout);
        PurpleIconLayout.setHorizontalGroup(
                PurpleIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );
        PurpleIconLayout.setVerticalGroup(
                PurpleIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );

        PurpleLabel.setBackground(new java.awt.Color(0, 0, 0));
        PurpleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        PurpleLabel.setForeground(new java.awt.Color(153, 153, 255));
        PurpleLabel.setText("> PURPLE - 9000");

        javax.swing.GroupLayout PurplePanelLayout = new javax.swing.GroupLayout(PurplePanel);
        PurplePanel.setLayout(PurplePanelLayout);
        PurplePanelLayout.setHorizontalGroup(
                PurplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PurplePanelLayout.createSequentialGroup()
                                .addComponent(PurpleIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PurpleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        PurplePanelLayout.setVerticalGroup(
                PurplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PurpleIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PurpleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PinkPanel.setBackground(new java.awt.Color(25, 37, 46));

        PinkIcon.setBackground(new java.awt.Color(255, 204, 204));
        PinkIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout PinkIconLayout = new javax.swing.GroupLayout(PinkIcon);
        PinkIcon.setLayout(PinkIconLayout);
        PinkIconLayout.setHorizontalGroup(
                PinkIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );
        PinkIconLayout.setVerticalGroup(
                PinkIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );

        PinkLabel.setBackground(new java.awt.Color(0, 0, 0));
        PinkLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        PinkLabel.setForeground(new java.awt.Color(255, 204, 204));
        PinkLabel.setText("> PINK - 8000");

        javax.swing.GroupLayout PinkPanelLayout = new javax.swing.GroupLayout(PinkPanel);
        PinkPanel.setLayout(PinkPanelLayout);
        PinkPanelLayout.setHorizontalGroup(
                PinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PinkPanelLayout.createSequentialGroup()
                                .addComponent(PinkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        PinkPanelLayout.setVerticalGroup(
                PinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PinkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Colors.setBackground(new java.awt.Color(25, 37, 46));

        ColorsLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        ColorsLabel.setForeground(new java.awt.Color(127, 253, 253));
        ColorsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColorsLabel.setText("Your Colors");
        ColorsLabel.setToolTipText("Unlock more colors with points");

        Color5.setBackground(new java.awt.Color(25, 37, 46));
        Color5.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout Color5Layout = new javax.swing.GroupLayout(Color5);
        Color5.setLayout(Color5Layout);
        Color5Layout.setHorizontalGroup(
                Color5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        Color5Layout.setVerticalGroup(
                Color5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        Color6.setBackground(new java.awt.Color(25, 37, 46));
        Color6.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout Color6Layout = new javax.swing.GroupLayout(Color6);
        Color6.setLayout(Color6Layout);
        Color6Layout.setHorizontalGroup(
                Color6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        Color6Layout.setVerticalGroup(
                Color6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 99, Short.MAX_VALUE)
        );

        Color3.setBackground(new java.awt.Color(25, 37, 46));
        Color3.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout Color3Layout = new javax.swing.GroupLayout(Color3);
        Color3.setLayout(Color3Layout);
        Color3Layout.setHorizontalGroup(
                Color3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        Color3Layout.setVerticalGroup(
                Color3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        Color1.setBackground(new java.awt.Color(127, 253, 253));
        Color1.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout Color1Layout = new javax.swing.GroupLayout(Color1);
        Color1.setLayout(Color1Layout);
        Color1Layout.setHorizontalGroup(
                Color1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        Color1Layout.setVerticalGroup(
                Color1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        Color2.setBackground(new java.awt.Color(25, 37, 46));

        javax.swing.GroupLayout Color2Layout = new javax.swing.GroupLayout(Color2);
        Color2.setLayout(Color2Layout);
        Color2Layout.setHorizontalGroup(
                Color2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        Color2Layout.setVerticalGroup(
                Color2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        Color4.setBackground(new java.awt.Color(25, 37, 46));
        Color4.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout Color4Layout = new javax.swing.GroupLayout(Color4);
        Color4.setLayout(Color4Layout);
        Color4Layout.setHorizontalGroup(
                Color4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        Color4Layout.setVerticalGroup(
                Color4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ColorsLayout = new javax.swing.GroupLayout(Colors);
        Colors.setLayout(ColorsLayout);
        ColorsLayout.setHorizontalGroup(
                ColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ColorsLayout.createSequentialGroup()
                                .addGroup(ColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ColorsLayout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addGroup(ColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(ColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(Color5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Color3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(Color1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(ColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(Color6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Color2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Color4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(ColorsLayout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(ColorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(32, Short.MAX_VALUE))
        );
        ColorsLayout.setVerticalGroup(
                ColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ColorsLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(ColorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Color2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Color1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Color4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(Color3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(ColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Color6, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                        .addComponent(Color5, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout BrowPanelLayout = new javax.swing.GroupLayout(BrowPanel);
        BrowPanel.setLayout(BrowPanelLayout);
        BrowPanelLayout.setHorizontalGroup(
                BrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BrowPanelLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(BrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(BrowPanelLayout.createSequentialGroup()
                                                .addComponent(ShopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(BrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(BrowPanelLayout.createSequentialGroup()
                                                                .addComponent(pointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(pointsCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(pointsBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(BrowPanelLayout.createSequentialGroup()
                                                .addGroup(BrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(BrowPanelLayout.createSequentialGroup()
                                                                .addGroup(BrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(AquaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(PinkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(BrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(PurplePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                                                .addComponent(YellowPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(RedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(OrangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(191, 191, 191)
                                                                .addComponent(Colors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(ShopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 27, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        BrowPanelLayout.setVerticalGroup(
                BrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BrowPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(BrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(BrowPanelLayout.createSequentialGroup()
                                                .addComponent(ShopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6))
                                        .addGroup(BrowPanelLayout.createSequentialGroup()
                                                .addGroup(BrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(pointsCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pointsBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ShopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(BrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Colors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(BrowPanelLayout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(RedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(OrangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(YellowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(PinkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(PurplePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(AquaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(116, Short.MAX_VALUE))
        );


        //*********************************************************************************************************************************************


        javax.swing.GroupLayout SetPanelLayout = new javax.swing.GroupLayout(SetPanel);
        SetPanel.setBackground(Color.YELLOW);
        SetPanel.setLayout(SetPanelLayout);
        SetPanelLayout.setHorizontalGroup(
                SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 803, Short.MAX_VALUE)
        );
        SetPanelLayout.setVerticalGroup(
                SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 740, Short.MAX_VALUE)
        );


        //*********************************************************************************************************************************************

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DefaultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OpenersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AssPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BrowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

        );
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DefaultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OpenersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AssPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BrowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    private void addOpenersButton(JPanel panel1) {
        final Color[] loginButtonColors = {UIUtils.COLOR_INTERACTIVE, Color.white};

        JLabel loginButton = new JLabel() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = UIUtils.get2dGraphics(g);
                super.paintComponent(g2);

                Insets insets = getInsets();
                int w = getWidth() - insets.left - insets.right;
                int h = getHeight() - insets.top - insets.bottom;
                g2.setColor(loginButtonColors[0]);
                g2.fillRoundRect(insets.left, insets.top, w, h, UIUtils.ROUNDNESS, UIUtils.ROUNDNESS);

                FontMetrics metrics = g2.getFontMetrics(UIUtils.FONT_GENERAL_UI);
                int x2 = (getWidth() - metrics.stringWidth(UIUtils.BUTTON_TEXT_LOGIN)) / 2;
                int y2 = ((getHeight() - metrics.getHeight()) / 2) + metrics.getAscent();
                g2.setFont(UIUtils.FONT_GENERAL_UI);
                g2.setColor(loginButtonColors[1]);
                g2.drawString(UIUtils.BUTTON_TEXT_LOGIN, x2, y2);
            }
        };

        loginButton.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                //loginEventHandler();
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                loginButtonColors[0] = UIUtils.COLOR_INTERACTIVE_DARKER;
                loginButtonColors[1] = UIUtils.OFFWHITE;
                loginButton.repaint();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                loginButtonColors[0] = UIUtils.COLOR_INTERACTIVE;
                loginButtonColors[1] = Color.white;
                loginButton.repaint();
            }
        });
        panel1.add(loginButton);
    }

    private void OpenersBtnActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Called");
        DefaultPanel.setVisible(false);
        OpenersPanel.setVisible(true);
        System.out.println(".");
    }

    private void setBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void OpenersBtnMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }


    public void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private JLabel loginButton = new JLabel() {
        @Override
        protected void paintComponent(Graphics g) {
            final Color[] loginButtonColors = {UIUtils.COLOR_INTERACTIVE, Color.white};
            Graphics2D g2 = UIUtils.get2dGraphics(g);
            super.paintComponent(g2);

            Insets insets = getInsets();
            int w = getWidth() - insets.left - insets.right;
            int h = getHeight() - insets.top - insets.bottom;
            g2.setColor(loginButtonColors[0]);
            g2.fillRoundRect(insets.left, insets.top, w, h, UIUtils.ROUNDNESS, UIUtils.ROUNDNESS);

            FontMetrics metrics = g2.getFontMetrics(UIUtils.FONT_GENERAL_UI);
            int x2 = (getWidth() - metrics.stringWidth(UIUtils.BUTTON_TEXT_LOGIN)) / 2;
            int y2 = ((getHeight() - metrics.getHeight()) / 2) + metrics.getAscent();
            g2.setFont(UIUtils.FONT_GENERAL_UI);
            g2.setColor(loginButtonColors[1]);
            g2.drawString(UIUtils.BUTTON_TEXT_LOGIN, x2, y2);

            loginButton.setBackground(UIUtils.COLOR_BACKGROUND);
            loginButton.setBounds(10, 10, 250, 44);
            loginButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        }
    };
    private JLabel AccentLabel;
    private JPanel LogoBorder;
    private JPanel MainPanel;
    private JPanel MenuPanel;
    private JLabel OpenersBtn;
    private JLabel assBtn;
    private JLabel browBtn;
    private JPanel DefaultPanel;
    private JLabel jLabel1;
    private javax.swing.JLabel mBtn;
    private javax.swing.JLabel sBtn;
    private javax.swing.JLabel setBtn;
    private javax.swing.JPanel winBtns;
    private javax.swing.JLabel xBtn;
    private JLabel lxicon;
    private JPanel OpenersPanel;
    private JPanel AssPanel;
    private JPanel BrowPanel;
    private JPanel SetPanel;
    private JScrollPane ScrollAss;
    private JTable AssTable;


    //Shop Panel
    private javax.swing.JPanel Color1;
    private javax.swing.JPanel Color2;
    private javax.swing.JPanel Color3;
    private javax.swing.JPanel Color4;
    private javax.swing.JPanel Color5;
    private javax.swing.JPanel Color6;
    private javax.swing.JPanel ColorRedIcon1;
    private javax.swing.JPanel Colors;
    private javax.swing.JLabel ColorsLabel;
    private javax.swing.JPanel AquaIcon;
    private javax.swing.JLabel AquaLabel;
    private javax.swing.JPanel AquaPanel;
    private javax.swing.JPanel OrangeIcon;
    private javax.swing.JPanel OrangePanel;
    private javax.swing.JPanel PinkIcon;
    private javax.swing.JLabel PinkLabel;
    private javax.swing.JPanel PinkPanel;
    private javax.swing.JPanel PurpleIcon;
    private javax.swing.JLabel PurpleLabel;
    private javax.swing.JPanel PurplePanel;
    private javax.swing.JPanel RedIcon;
    private javax.swing.JLabel RedLabel;
    private javax.swing.JPanel RedPanel;
    private javax.swing.JPanel ShopBar;
    private javax.swing.JLabel ShopLabel;
    private javax.swing.JPanel YellowIcon;
    private javax.swing.JLabel YellowLabel;
    private javax.swing.JPanel YellowPanel;
    private javax.swing.JLabel orangeLabel;
    private javax.swing.JProgressBar pointsBar;
    private javax.swing.JLabel pointsCounter;
    private javax.swing.JLabel pointsLabel;


    //Toaster
    private Toaster toaster;
    // End of variables declaration
}
